
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/.packages
    - pubspec.yaml

linter:
  rules:
    # Puedes añadir reglas aquí, pero mantener la lista pequeña ayuda al rendimiento
    avoid_print: true