// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6dLUexftfjqAFmla4gbAwAocTCsMij8Y',
    appId: '1:85110058111:web:46a3e4e6c8bd761b55a34a',
    messagingSenderId: '85110058111',
    projectId: 'music-stereo',
    authDomain: 'music-stereo.firebaseapp.com',
    storageBucket: 'music-stereo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZw9wpZDmsWA83VxbxaNQZ-AkasxQqVg',
    appId: '1:85110058111:android:fab376947b813ddc55a34a',
    messagingSenderId: '85110058111',
    projectId: 'music-stereo',
    storageBucket: 'music-stereo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRSfq05GUCwHO1PkgV_cO2XJrH0x7yfE',
    appId: '1:85110058111:ios:e081ec9027e8b84955a34a',
    messagingSenderId: '85110058111',
    projectId: 'music-stereo',
    storageBucket: 'music-stereo.firebasestorage.app',
    iosBundleId: 'com.example.musicStereo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRSfq05GUCwHO1PkgV_cO2XJrH0x7yfE',
    appId: '1:85110058111:ios:e081ec9027e8b84955a34a',
    messagingSenderId: '85110058111',
    projectId: 'music-stereo',
    storageBucket: 'music-stereo.firebasestorage.app',
    iosBundleId: 'com.example.musicStereo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6dLUexftfjqAFmla4gbAwAocTCsMij8Y',
    appId: '1:85110058111:web:b0176fd816d7a5cc55a34a',
    messagingSenderId: '85110058111',
    projectId: 'music-stereo',
    authDomain: 'music-stereo.firebaseapp.com',
    storageBucket: 'music-stereo.firebasestorage.app',
  );
}
